<?php
/**
 * Maid4Condos — default content.
 *
 * Every fact in this file comes from maid4condos.com (services, checklists,
 * service areas, testimonials, FAQs, guarantees, company details). Nothing is
 * invented: no prices, awards, statistics, ratings or guarantees appear here
 * unless the business publishes them.
 *
 * The database mirrors this content. When a table is empty — or MySQL is not
 * available — the public site falls back to these values so the site is always
 * complete, and the admin panel seeds editable copies on first run.
 */

return [

    // -----------------------------------------------------------------------
    // Site settings (key => [group, type, value, label])
    // -----------------------------------------------------------------------
    'settings' => [
        'site_name'            => ['general', 'text', 'Maid4Condos', 'Site name'],
        'site_legal_name'      => ['general', 'text', 'Maid4Condos', 'Legal name'],
        'site_tagline'         => ['general', 'text', 'Condo Cleaning Services You Can Count On', 'Tagline'],
        'site_description'     => ['general', 'textarea', 'Maid4Condos provides meticulous condo and home cleaning across Toronto and the GTA — basic, deep and move in/move out packages with flexible scheduling and a 24 hour guarantee.', 'Short business description'],
        'default_meta_title'   => ['seo', 'text', 'Condo Cleaning Services Toronto | Maid4Condos', 'Default meta title'],
        'default_meta_description' => ['seo', 'textarea', 'Maid4Condos offers professional condo cleaning services in Toronto. Meticulous attention to detail, transparent pricing and flexible scheduling. Request your quote today.', 'Default meta description'],
        'og_image'             => ['seo', 'text', 'assets/images/cleaned-living-room.jpg', 'Social share image'],
        'robots_policy'        => ['seo', 'select', 'index,follow', 'Robots policy'],
        'phone'                => ['contact', 'text', '647-822-0601', 'Phone'],
        'phone_display'        => ['contact', 'text', '(647) 822-0601', 'Phone (display)'],
        'email'                => ['contact', 'text', 'info@maid4condos.com', 'General email'],
        'booking_email'        => ['contact', 'text', 'bookings@maid4condos.com', 'Bookings email'],
        'address_street'       => ['contact', 'text', '60 Atlantic Ave., Suite 200', 'Street address'],
        'address_city'         => ['contact', 'text', 'Toronto', 'City'],
        'address_region'       => ['contact', 'text', 'ON', 'Province / region'],
        'address_postal'       => ['contact', 'text', 'M6K 1X9', 'Postal code'],
        'address_country'      => ['contact', 'text', 'Canada', 'Country'],
        'office_hours'         => ['contact', 'textarea', "Monday – Friday: 8:00 am – 6:00 pm\nSaturday & Sunday: 9:00 am – 4:00 pm", 'Office hours'],
        'service_hours'        => ['contact', 'text', 'Residential cleanings are scheduled Monday – Friday between 8:00 am and 6:00 pm. We do not currently offer evening or weekend residential bookings.', 'Service window note'],
        'map_query'            => ['contact', 'text', '60 Atlantic Ave, Toronto, ON M6K 1X9', 'Google Maps query'],
        'opening_hours_schema' => ['contact', 'text', 'Mo-Fr 08:00-18:00|Sa-Su 09:00-16:00', 'Structured opening hours'],
        'social_facebook'      => ['social', 'text', 'https://www.facebook.com/Maid4Condos/', 'Facebook URL'],
        'social_instagram'     => ['social', 'text', 'https://www.instagram.com/maid4condos/', 'Instagram URL'],
        'social_twitter'       => ['social', 'text', 'https://twitter.com/Maid4Condos', 'X / Twitter URL'],
        'reviews_site_count'   => ['social', 'text', '250', 'Reviews on maid4condos.com'],
        'reviews_yelp_count'   => ['social', 'text', '31', 'Reviews on Yelp'],
        'reviews_google_count' => ['social', 'text', '77', 'Reviews on Google'],
        'guarantee_text'       => ['trust', 'textarea', 'If you are not 100% satisfied with the quality of cleaning of any of the serviced areas, and your home is as described and in average condition, and you advise the office within 24 hours of your service, Maid4Condos will send a cleaner back to address any areas in which we fell short within 3 days of your original scheduled cleaning.', 'Satisfaction guarantee'],
        'liability_coverage'   => ['trust', 'text', '5,000,000', 'Liability coverage (CAD)'],
        'ga4_measurement_id'   => ['analytics', 'text', '', 'Google Analytics 4 measurement ID'],
        'analytics_enabled'    => ['analytics', 'select', '1', 'Analytics enabled'],
        'quote_success_title'  => ['forms', 'text', 'Thank you! Your request has been received.', 'Quote success heading'],
        'quote_success_text'   => ['forms', 'textarea', 'A member of our team will contact you shortly to confirm the details and pricing for your cleaning. If you need to reach us sooner, call (647) 822-0601 or email info@maid4condos.com.', 'Quote success message'],
        'contact_success_text' => ['forms', 'textarea', 'Thanks for getting in touch. Our team will reply to your message shortly.', 'Contact success message'],
    ],

    // -----------------------------------------------------------------------
    // Cleaning packages (services)
    // -----------------------------------------------------------------------
    'services' => [
        [
            'slug'         => 'basic-cleaning',
            'name'         => 'Basic Clean',
            'eyebrow'      => 'Everyday upkeep',
            'tagline'      => 'A 30+ point checklist that is anything but basic',
            'summary'      => 'Our foundation package: a detailed 30+ point clean that we check twice, built for condos that are already in average condition.',
            'price_from'   => '119.99',
            'image'        => 'cleaning-kitchen-cabinets',
            'hero_image'   => 'cleaning-kitchen-cabinets',
            'duration_note' => 'Most condos are complete in under 4 hours.',
            'best_paired'  => 'Weekly or bi-weekly AutoPilot schedule',
            'meta_title'   => 'Basic Cleaning Package Toronto | Maid4Condos',
            'meta_description' => 'A detailed 30+ point basic cleaning checklist for Toronto condos — checked twice so the job is always done right. Get your quote from Maid4Condos.',
            'intro'        => [
                'You are looking for a Basic Cleaning Package that is anything but basic. With a detailed 30+ point checklist for a simple yet thorough clean — and a second check just to be sure we have done the job right — this package is perfect if you crave a tidy home but cannot find the time to do it yourself.',
                'We recommend pairing the Basic Clean with a weekly or bi-weekly AutoPilot schedule so your home is effectively maintained. AutoPilot provides up to 20% off per visit.',
            ],
            'who_for'      => [
                'Condos and apartments in average condition',
                'Busy professionals who want their home reset regularly',
                'Renters and owners who want a dependable recurring clean',
                'Anyone maintaining a home that has been cleaned within the last few weeks',
            ],
            'checklist'    => [
                'Bathrooms' => [
                    'Bathtub and shower enclosure',
                    'Inside, out and behind toilet',
                    'Lights, mirrors, sink, countertops',
                    'Vacuum ceiling fan cover',
                    'Light switches, door knobs',
                    'Empty garbage bin',
                    'Vacuum / mop floors',
                ],
                'Bedrooms' => [
                    'Make beds',
                    'Tidy any clothing',
                    'Dust counters, table tops, picture frames',
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                ],
                'Kitchen' => [
                    'If dishwasher is empty, start a new load',
                    'If dishwasher is full, put away clean dishes',
                    'Microwave inside',
                    'Stove top',
                    'Fridge front polished',
                    'Backsplash, counter tops, cupboard fronts',
                    'Sink',
                    'Wipe light switches & door knobs',
                    'Replace garbage and recycling liners',
                    'Vacuum / mop floors',
                ],
                'Living & dining room' => [
                    'General tidying',
                    'Tidy sofa seating',
                    'Table tops, picture frames, window ledges',
                    'Clean mirrors and polish ornaments',
                    'Wipe telephones, switches, door knobs',
                    'Vacuum / mop floors',
                ],
                'Laundry room' => [
                    'Clear air vent',
                    'Clear lint trap',
                ],
            ],
            'benefits'     => [
                'Everything on the 30+ point checklist, verified twice',
                'The most economical way to keep a condo consistently clean',
                'Up to 20% off per visit on an AutoPilot schedule',
                'All standard supplies and equipment included',
            ],
            'faqs'         => [
                ['What condition does my condo need to be in?', 'A basic cleaning is designed for homes in average condition. If it has been a while, or if there has been a lot of activity, a Basic Plus or Deep Clean gives us the extra time the space needs.'],
                ['Can I add the fridge, oven or windows?', 'Yes. Inside Oven, Inside Fridge, Inside Windows, a laundry load, vacuum delivery and GermBlasters disinfection can each be added to a basic cleaning.'],
                ['How often should I book?', 'Most clients choose weekly or bi-weekly. Bi-weekly is our recommended maintenance schedule and comes with a 15% discount per visit.'],
            ],
        ],
        [
            'slug'         => 'basic-plus',
            'name'         => 'Basic Plus',
            'eyebrow'      => 'A little extra love',
            'tagline'      => 'The same checklist with 10–15% more time on site',
            'summary'      => 'Identical to the Basic Clean checklist, with 10–15% more time allocated for homes that need extra attention.',
            'price_from'   => '149.99',
            'image'        => 'cleaning-vacuum-kitchen',
            'hero_image'   => 'cleaning-vacuum-kitchen',
            'duration_note' => '10–15% more time than a Basic Clean.',
            'best_paired'  => 'Weekly or bi-weekly AutoPilot schedule',
            'meta_title'   => 'Basic Plus Cleaning Package Toronto | Maid4Condos',
            'meta_description' => 'Go beyond our basic cleaning package. Basic Plus gives 10–15% more time so your Toronto condo gets the attention it deserves. Request a quote.',
            'intro'        => [
                'Does your home feel like it has lost its sparkle? If you are recovering from hosting house guests, or simply have not cleaned in a while, or you have pets or kids — the Basic Plus Cleaning Package is for you.',
                'This package includes the same checklist items as the Basic Clean, but provides an additional 10–15% more time on site when a little extra love and care is needed.',
            ],
            'who_for'      => [
                'Homes with pets or children',
                'Condos recovering after hosting guests or a busy stretch',
                'Anyone who wants the full checklist done without rushing',
                'Clients stepping back into a regular cleaning routine',
            ],
            'checklist'    => [
                'Bathrooms' => [
                    'Bathtub and shower enclosure',
                    'Inside, out and behind toilet',
                    'Lights, mirrors, sink, countertops',
                    'Vacuum ceiling fan cover',
                    'Light switches, door knobs',
                    'Empty garbage bin',
                    'Vacuum / mop floors',
                ],
                'Bedrooms' => [
                    'Make bed',
                    'Tidy any clothing',
                    'Dust counters, table tops, picture frames',
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                ],
                'Kitchen' => [
                    'If dishwasher is empty, start a new load',
                    'If dishwasher is full, put away clean dishes',
                    'Microwave inside',
                    'Stove top',
                    'Fridge front polished',
                    'Backsplash, counter tops, cupboard fronts',
                    'Sink',
                    'Wipe light switches & door knobs',
                    'Replace garbage and recycling liners',
                    'Vacuum / mop floors',
                ],
                'Living & dining room' => [
                    'General tidying',
                    'Tidy sofa seating',
                    'Table tops, picture frames, window ledges',
                    'Clean mirrors and polish ornaments',
                    'Wipe telephones, switches, door knobs',
                    'Vacuum / mop floors',
                ],
                'Laundry room' => [
                    'Clear air vent',
                    'Clear lint trap',
                ],
            ],
            'benefits'     => [
                'The complete Basic checklist, minus the time pressure',
                'Ideal when pets, kids or guests have left their mark',
                'Same up to 20% AutoPilot discount when booked on a schedule',
                'Supplies and equipment included',
            ],
            'faqs'         => [
                ['How is this different from the Basic Clean?', 'The checklist is identical. Basic Plus simply allocates 10–15% more time to the visit so we can work through everything without rushing.'],
                ['Should I choose Basic Plus or a Deep Clean?', 'Choose Basic Plus if the home is generally maintained and just needs more time. Choose a Deep Clean if baseboards, under furniture, window ledges and build-up need addressing.'],
                ['Can I combine it with extras?', 'Absolutely — oven, fridge, interior windows, laundry, vacuum delivery and GermBlasters disinfection can all be added.'],
            ],
        ],
        [
            'slug'         => 'deep-cleaning',
            'name'         => 'Deep Clean',
            'eyebrow'      => 'Reset your space',
            'tagline'      => 'Every inch of your condo, spotless',
            'summary'      => 'A thorough top-to-bottom clean that clears built-up dirt, dust and grime — baseboards, under furniture and all the places a routine clean misses.',
            'price_from'   => '169.99',
            'image'        => 'cleaning-floors',
            'hero_image'   => 'cleaning-floors',
            'duration_note' => 'Booked with extra time for detail work.',
            'best_paired'  => 'A Deep Clean first, then AutoPilot maintenance',
            'meta_title'   => 'Residential Deep Cleaning Services Toronto | Maid4Condos',
            'meta_description' => 'Our deep cleaning package makes your Toronto condo look brand new — baseboards, under furniture and built-up grime addressed. Book with Maid4Condos.',
            'intro'        => [
                'A condo deep cleaning by Maid4Condos is what you need if your regular cleanings have fallen behind. Our deep cleaning service is perfect for those who want to feel like they are walking into their home for the first time.',
                'With our custom deep cleaning service we make sure every inch of your condo or apartment is spotless — removing dirt, dust, stains and grime. After the initial deep clean, scheduled visits are advised to keep it that way, or you can let Maid4Condos maintain it on a weekly, bi-weekly or monthly basis.',
                'A deep clean should be done at least once a year to keep you and your family healthy.',
            ],
            'who_for'      => [
                'Homes where regular cleaning has fallen behind',
                'Spring cleaning, or preparing a property to list for sale',
                'Before hosting family for the holidays or a get-together',
                'First-time clients who want a true reset before a maintenance schedule',
            ],
            'checklist'    => [
                'Bathrooms' => [
                    'Bathtub and shower enclosure',
                    'Inside, out and behind toilet',
                    'Lights, mirrors, sink, countertops',
                    'Vacuum ceiling fan cover',
                    'Light switches, door knobs',
                    'Empty garbage bin',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                ],
                'Bedrooms' => [
                    'Make bed',
                    'Tidy any clothing',
                    'Dust counters, table tops, picture frames',
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Kitchen' => [
                    'If dishwasher is empty, start a new load',
                    'If dishwasher is full, put away clean dishes',
                    'Microwave inside',
                    'Stove top',
                    'Fridge front polished',
                    'Backsplash, counter tops, cupboard fronts',
                    'Sink',
                    'Wipe light switches & door knobs',
                    'Replace garbage and recycling liners',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Living & dining room' => [
                    'General tidying',
                    'Tidy sofa seating',
                    'Table tops, picture frames, window ledges',
                    'Clean mirrors and dust ornaments',
                    'Wipe telephones, switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Clean under and behind furniture',
                    'Vacuum sofa seating',
                ],
                'Laundry room' => [
                    'Clear air vent',
                    'Clear lint trap',
                    'Wipe washer and dryer',
                    'Clean floors',
                ],
            ],
            'benefits'     => [
                'A healthy home — built-up allergens, grime and dust removed',
                'More free time in the weeks and months afterwards',
                'Improves how a property shows to potential buyers',
                'A clean, calm home to walk into after a long day',
            ],
            'faqs'         => [
                ['How long does a deep clean take?', 'Deep cleans are allocated significantly more time than a basic clean. The exact duration depends on the size, the number of bathrooms and the condition of the property.'],
                ['Should the condo be empty?', 'No. A deep clean is for an occupied home. If the property will be completely empty or vacant, the Move In / Move Out Clean is the right package.'],
                ['How often should I deep clean?', 'At least once a year. Many clients start with a deep clean and then maintain the result with a recurring basic or basic plus schedule.'],
            ],
        ],
        [
            'slug'         => 'deep-plus',
            'name'         => 'Deep Plus',
            'eyebrow'      => 'Extra elbow grease',
            'tagline'      => 'The deep clean checklist with more time to work',
            'summary'      => 'The full deep cleaning checklist with 10–15% more time for homes that need serious attention or have not been deep cleaned in a long while.',
            'price_from'   => '199.99',
            'image'        => 'cleaning-vacuum-rug',
            'hero_image'   => 'cleaning-vacuum-rug',
            'duration_note' => '10–15% more time than a Deep Clean.',
            'best_paired'  => 'AutoPilot maintenance after the reset',
            'meta_title'   => 'Deep Plus Cleaning Package Toronto | Maid4Condos',
            'meta_description' => 'Deep Plus gives the full deep cleaning checklist 10–15% more time for homes that need extra attention. Book Toronto condo cleaning with Maid4Condos.',
            'intro'        => [
                'Does your home feel like it needs a little extra elbow grease? If you have just hosted guests, or you simply have not deep cleaned in a while, or you have pets or kids — the Deep Plus Cleaning Package may be for you.',
                'This package includes the same checklist items as the Deep Clean, but provides 10–15% more time on site when a little extra love and care is needed.',
            ],
            'who_for'      => [
                'Condos that have gone a long time between deep cleans',
                'Larger units or homes with multiple bathrooms',
                'Households with pets or children',
                'Clients who want the deep clean result without time pressure',
            ],
            'checklist'    => [
                'Bathrooms' => [
                    'Bathtub and shower enclosure',
                    'Inside, out and behind toilet',
                    'Lights, mirrors, sink, countertops',
                    'Vacuum ceiling fan cover',
                    'Light switches, door knobs',
                    'Empty garbage bin',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                ],
                'Bedrooms' => [
                    'Make bed',
                    'Tidy any clothing',
                    'Dust counters, table tops, picture frames',
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Kitchen' => [
                    'If dishwasher is empty, start a new load',
                    'If dishwasher is full, put away clean dishes',
                    'Microwave inside',
                    'Stove top',
                    'Fridge front polished',
                    'Backsplash, counter tops, cupboard fronts',
                    'Sink',
                    'Wipe light switches & door knobs',
                    'Replace garbage and recycling liners',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Living & dining room' => [
                    'General tidying',
                    'Tidy sofa seating',
                    'Table tops, picture frames, window ledges',
                    'Clean mirrors and dust ornaments',
                    'Wipe telephones, switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Clean under and behind furniture',
                    'Vacuum sofa seating',
                ],
                'Laundry room' => [
                    'Clear air vent',
                    'Clear lint trap',
                    'Wipe washer and dryer',
                    'Clean floors',
                ],
            ],
            'benefits'     => [
                'The full deep clean checklist without the rush',
                'Built for larger units and busier households',
                'Removes build-up that a basic clean simply cannot reach',
                'Puts you in the best position to maintain with AutoPilot',
            ],
            'faqs'         => [
                ['Deep Clean or Deep Plus?', 'The checklist is the same. Deep Plus adds 10–15% more time, which is the right call when it has been a long while, or the home is larger than average.'],
                ['Can you clean behind heavy furniture?', 'For the health and safety of our cleaners we do not move anything heavier than 30 lbs. If you need an area behind heavy furniture cleaned, please move the item before we arrive.'],
                ['Do you clean inside appliances?', 'Inside Oven and Inside Fridge can be added to any deep clean — and both are included by default in the Move In / Move Out package.'],
            ],
        ],
        [
            'slug'         => 'move-in-move-out',
            'name'         => 'Move In / Move Out',
            'eyebrow'      => 'Showroom ready',
            'tagline'      => 'A complete reset for empty condos',
            'summary'      => 'Designed for vacant units: inside and outside of everything, including appliances, cabinets, drawers and air vents. Supplies and equipment included.',
            'price_from'   => '249.99',
            'image'        => 'moving-boxes',
            'hero_image'   => 'moving-boxes',
            'duration_note' => 'Supplies, equipment and the vacuum are included.',
            'best_paired'  => 'One-time, before or after your move',
            'meta_title'   => 'Move In / Move Out Cleaning Service Toronto | Maid4Condos',
            'meta_description' => 'Toronto move in and move out cleaning for empty condos — appliances, cabinets, drawers and vents cleaned inside and out. Get your quote from Maid4Condos.',
            'intro'        => [
                'Moving out of your condo, or into a new one? Leave behind a clean, well cared for home — or start life fresh in your new place with a custom condo cleaning by Maid4Condos. We specialise in move in and move out condo cleaning.',
                'One of the most challenging things about moving is knowing there is a tonne of cleaning to be done. Your landlord may also require a deep clean of the unit before you leave — why not let the professionals take care of it?',
                'This service is designed for empty spaces and to get them back into like-new shape. We clean inside and outside of everything, including appliances, cabinets, drawers and air vents. If you need to get your space showroom ready, this is the service for you.',
                'A move in / move out cleaning is also ideal for real estate agents showing units, tenants who want their deposit back, and landlords preparing a unit for a new tenant.',
            ],
            'who_for'      => [
                'Tenants moving out who want their unit left in excellent condition',
                'Buyers and renters moving into a freshly cleaned space',
                'Landlords and property managers turning a unit over',
                'Real estate agents preparing a condo to show',
            ],
            'checklist'    => [
                'Bathrooms' => [
                    'Bathtub and shower enclosure',
                    'Inside, out and behind toilet',
                    'Lights, mirrors, sink, countertops',
                    'Vacuum ceiling fan cover',
                    'Light switches, door knobs',
                    'Empty garbage bin',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe vanity inside and out',
                ],
                'Bedrooms' => [
                    'Dust counters, table tops, picture frames',
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Kitchen' => [
                    'Inside fridge and oven',
                    'Stove top',
                    'Fridge front polished',
                    'Microwave inside',
                    'Backsplash, counter tops, cupboard fronts',
                    'Sink',
                    'Wipe light switches & door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                    'Wipe inside cabinets',
                    'Wipe inside drawers',
                ],
                'Living & dining room' => [
                    'Clean mirrors and polish ornaments',
                    'Wipe switches, door knobs',
                    'Vacuum / mop floors',
                    'Wipe baseboards',
                    'Wipe window ledges',
                ],
                'Laundry room' => [
                    'Clear air vent',
                    'Clear lint trap',
                    'Wipe washer and dryer',
                    'Clean floors',
                ],
            ],
            'benefits'     => [
                'Cabinets, drawers, appliances and vents cleaned inside and out',
                'All supplies, equipment and the vacuum are included',
                'Helps protect your deposit and satisfy lease requirements',
                'Gets a unit showroom ready for photos, showings or a new tenant',
            ],
            'faqs'         => [
                ['Does the unit need to be empty?', 'Yes — this package is designed for vacant spaces so we can reach inside cabinets, drawers and appliances without obstruction. For an occupied home, choose a Deep Clean or Deep Plus.'],
                ['Is the vacuum included?', 'Yes. All supplies, equipment and cleaning products are included for moving cleanings.'],
                ['Do you remove construction debris or clean a renovation site?', 'No. We are a finishing crew: we do the final detailed clean before a property is returned or delivered. We do not work in construction zones or remove construction debris.'],
            ],
        ],
        [
            'slug'         => 'recurring-cleaning',
            'name'         => 'Recurring Cleaning (AutoPilot)',
            'eyebrow'      => 'Set it and relax',
            'tagline'      => 'Weekly, bi-weekly or monthly — save up to 20%',
            'summary'      => 'Our AutoPilot schedule keeps your condo consistently clean. Choose weekly, bi-weekly or monthly, save up to 20% per visit, and change or skip dates with enough notice.',
            'price_from'   => null,
            'image'        => 'cleaned-living-room',
            'hero_image'   => 'cleaned-living-room',
            'duration_note' => 'No contracts required for residential AutoPilot clients.',
            'best_paired'  => 'Starts with a Basic, Basic Plus or Deep Clean',
            'meta_title'   => 'Recurring Cleaning Schedule Toronto | Maid4Condos AutoPilot',
            'meta_description' => 'Weekly, bi-weekly or monthly condo cleaning in Toronto with up to 20% off per visit. Join AutoPilot by Maid4Condos and never think about cleaning again.',
            'intro'        => [
                'The more often we service your home, the less it costs you per visit. AutoPilot is our recurring cleaning schedule: choose weekly, bi-weekly or monthly and we take care of the rest.',
                'Normally, the more often we service your home, the less it will cost you per visit. With an AutoPilot schedule, Maid4Condos brings the cleaning supplies you need so you do not have to buy them (unless you require specific products due to allergies or environmental preferences).',
                'Weekly and bi-weekly visits are not only more cost effective, they are also healthier. A routine clean reduces allergens, bacteria and other health concerns for your family.',
            ],
            'who_for'      => [
                'Busy households and professionals with full schedules',
                'Families, or anyone who entertains often',
                'Elderly or disabled clients who need a regular helping hand',
                'Condo owners and renters who want a permanently tidy home',
            ],
            'checklist'    => [
                'Weekly' => [
                    'Ideal for busy lifestyles and lots of social obligations',
                    '20% off every visit — the most economical service',
                    'A consistently maintained, allergen-light home',
                ],
                'Bi-weekly (recommended)' => [
                    'Our most popular schedule and recommended maintenance interval',
                    '15% off every visit',
                    'Great balance of upkeep and value for most homes',
                ],
                'Monthly' => [
                    'Typically paired with a deep cleaning package for a thorough service',
                    '5% off every visit',
                    'Suits homes that do not entertain often',
                ],
            ],
            'benefits'     => [
                'Up to 20% off every visit depending on frequency',
                'No contract required for residential AutoPilot clients',
                'Reschedule or skip a visit with enough notice, no problem',
                'Email reminder 5 days before and SMS reminder 3 days before each visit',
                'If your date lands on a holiday we move it to the next available date and let you know',
            ],
            'faqs'         => [
                ['Do I have to sign a contract?', 'No. AutoPilot clients do not commit to a contract, but by using our services you do agree to our Cleaning Service Agreement terms. Corporate clients have separate service agreements.'],
                ['Can I change a future date?', 'Yes. Let us know as far in advance as possible and we will reschedule, skip or change a future date — as long as you are outside the cancellation policy there is no issue.'],
                ['What happens if my cleaning falls on a holiday?', 'We move your cleaning to the next available date and communicate the change to you. By default we move it to the following day unless that day is already booked.'],
                ['How do frequency discounts work?', 'Weekly visits are discounted 20%, bi-weekly 15% and monthly 5%. Customisable rates are available for daily service or high-volume requirements.'],
            ],
        ],
    ],

    // -----------------------------------------------------------------------
    // Add-on services
    // -----------------------------------------------------------------------
    'extras' => [
        [
            'slug'     => 'germblasters',
            'name'     => 'GermBlasters Disinfection',
            'summary'  => 'Hospital-grade, Health Canada and EPA approved disinfection that is non-toxic, fragrance free and safe around children and pets.',
            'details'  => 'A molecular-level disinfection service for homes, offices and commercial spaces. The solution has a 0-0-0 SDS rating, is NSF certified (no rinse required) for food contact surfaces, and is effective against a broad spectrum of viruses and bacteria.',
        ],
        [
            'slug'     => 'inside-oven',
            'name'     => 'Inside Oven',
            'summary'  => 'A full interior oven clean, available with Basic, Basic Plus and Deep cleanings — and included by default in the Move In / Move Out package.',
            'details'  => 'If your oven has a self-cleaning cycle, please start it at least 24 hours before your service for the best results. Our staff arrive equipped with Easy-Off.',
        ],
        [
            'slug'     => 'inside-fridge',
            'name'     => 'Inside Fridge',
            'summary'  => 'All shelving, drawers and nooks cleaned inside your refrigerator. Included by default in the Move In / Move Out package.',
            'details'  => 'Please purge anything you no longer want or need before we arrive. We are not able to effectively clean freezers and instead give them a quick wipe.',
        ],
        [
            'slug'     => 'inside-windows',
            'name'     => 'Inside Windows',
            'summary'  => 'Interior window cleaning that brings more light into your home, for Basic, Basic Plus, Deep and Move In / Move Out cleanings.',
            'details'  => 'Please remove all screens before we arrive to avoid fragile clips being broken. We clean interior windows up to 9 ft tall; exterior windows are not included.',
        ],
        [
            'slug'     => 'vacuum-delivery',
            'name'     => 'Vacuum Delivery',
            'summary'  => 'If you do not have a vacuum, we will bring one so floors, surfaces, baseboards, ceiling vents and under-furniture areas can be properly cleaned.',
            'details'  => 'The Move In / Move Out package already includes the vacuum by default.',
        ],
        [
            'slug'     => 'laundry-load',
            'name'     => 'Laundry Load',
            'summary'  => 'One wash and fold load, most often used for bedding linens. Additional loads can be arranged — just let us know.',
            'details'  => 'If you book this extra, please contact our office to tell us exactly what you would like laundered so we can plan the visit and charge accordingly.',
        ],
    ],

    // -----------------------------------------------------------------------
    // Service frequencies (real discounts published by Maid4Condos)
    // -----------------------------------------------------------------------
    'frequencies' => [
        ['slug' => 'weekly',    'label' => 'Weekly',            'discount' => '20% off', 'note' => 'Most economical — ideal for busy lifestyles.', 'recommended' => false],
        ['slug' => 'bi-weekly', 'label' => 'Bi-weekly',         'discount' => '15% off', 'note' => 'Our most popular schedule and recommended interval.', 'recommended' => true],
        ['slug' => 'monthly',   'label' => 'Monthly',           'discount' => '5% off',  'note' => 'Suits homes that do not entertain often.', 'recommended' => false],
        ['slug' => 'one-time',  'label' => 'One time',          'discount' => 'No discount', 'note' => 'A single visit with no ongoing commitment.', 'recommended' => false],
    ],

    // -----------------------------------------------------------------------
    // Service areas
    // -----------------------------------------------------------------------
    'areas' => [
        ['name' => 'Liberty Village',      'note' => 'Our home base — the corporate office is on Atlantic Avenue.'],
        ['name' => 'Queen West',           'note' => 'Condo corridors from Bathurst to Ossington and beyond.'],
        ['name' => 'King West',            'note' => 'High-rise towers and lofts in the entertainment district.'],
        ['name' => 'Fort York',            'note' => 'New builds and lakeside condominium communities.'],
        ['name' => 'City Place',           'note' => 'Downtown high-rise condominium living.'],
        ['name' => 'Lakeshore Blvd',       'note' => 'Waterfront condos from Bathurst to the Humber.'],
        ['name' => 'Distillery District',  'note' => 'Loft conversions and historic brick buildings.'],
        ['name' => 'Yorkville',            'note' => 'Upscale condominium and boutique residences.'],
        ['name' => 'Downtown Toronto',     'note' => 'The core, and everything in between.'],
        ['name' => 'North York',           'note' => 'Condominium communities along the Yonge corridor.'],
        ['name' => 'Greater Toronto Area', 'note' => 'We currently service within the GTA and surrounding areas.'],
    ],

    // -----------------------------------------------------------------------
    // Homepage content blocks
    // -----------------------------------------------------------------------
    'home' => [
        'hero' => [
            'eyebrow'   => 'Toronto & the GTA',
            'title'     => 'Professional Cleaning Services You Can Count On',
            'subtitle'  => 'Maid4Condos is a family run Toronto cleaning company built for condo living — meticulous attention to detail, transparent pricing and scheduling that flexes around your life.',
            'primary_cta'   => ['label' => 'Get a quote', 'route' => 'get-a-quote'],
            'secondary_cta' => ['label' => 'Explore services', 'route' => 'services'],
            'bullets'   => [
                'Professional, background-checked cleaners',
                'Reliable service and a 24 hour guarantee',
                'Flexible scheduling — weekly to one-time',
                'Serving Toronto & the GTA',
            ],
            'image'     => 'hero-cleaning-modern-home',
        ],
        'trust' => [
            'heading' => 'Why Toronto keeps us on speed dial',
            'intro'   => 'Because time is precious. Here is what every Maid4Condos cleaning comes with.',
            'items'   => [
                ['icon' => 'badge',  'title' => 'A 24 hour guarantee', 'text' => 'Not delighted with the clean? Tell the office within 24 hours and we will return to make it right.'],
                ['icon' => 'shield', 'title' => 'Bonded & insured',   'text' => '5,000,000 in liability coverage, WSIB covered staff and a fully bonded team.'],
                ['icon' => 'team',   'title' => 'True employees',      'text' => 'Every cleaner is a Maid4Condos employee — never an independent contractor.'],
                ['icon' => 'spark',  'title' => 'Master class trained', 'text' => 'Background checked, cleaning master class trained and certified.'],
                ['icon' => 'calendar', 'title' => 'Flexible scheduling', 'text' => 'Weekly, bi-weekly, monthly or one-time — with up to 20% off recurring visits.'],
                ['icon' => 'leaf',   'title' => 'Considered products', 'text' => 'Professional grade, biodegradable products from trusted brands.'],
            ],
        ],
        'why' => [
            'heading' => 'Because we care',
            'intro'   => 'Brooms are great, though they rarely make you fall back in love with your home — but we can. We are not just strangers coming to clean your house; we are your partners-in-clean.',
            'points'  => [
                '100% satisfaction guarantee',
                'Attention to detail on every checklist item',
                'A personal touch, and well supervised staff',
                'Timely and flexible service',
                'Customer service that goes above and beyond',
            ],
        ],
        'how' => [
            'heading' => 'How it works',
            'intro'   => 'Four simple steps from first click to a spotless home.',
            'steps'   => [
                ['title' => 'Choose your service', 'text' => 'Pick the package that fits: Basic, Basic Plus, Deep, Deep Plus or Move In / Move Out.'],
                ['title' => 'Tell us about your space', 'text' => 'Share your neighbourhood, bedrooms, bathrooms and approximate square footage.'],
                ['title' => 'Receive your quote', 'text' => 'We confirm the details, pricing and the visit window that works for you.'],
                ['title' => 'Enjoy a clean home', 'text' => 'Our team arrives, works through the checklist and leaves your space refreshed.'],
            ],
        ],
        'areas_intro' => 'Maid4Condos provides cleaning services across the entire Toronto region. These are some of the neighbourhoods we service — we are not limited to them, so tell us your postal code and we will confirm.',
        'final' => [
            'heading' => 'Ready for a cleaner space?',
            'text'    => 'Tell us about your condo and we will send a clear, no-obligation quote. It takes about a minute.',
        ],
    ],

    // -----------------------------------------------------------------------
    // About page
    // -----------------------------------------------------------------------
    'about' => [
        'heading' => 'Don’t want strangers in your home? Neither would we.',
        'intro'   => 'Here is a bit about who is coming through your door.',
        'story'   => [
            'We tried the corporate life — it was too impersonal. We wanted to support ourselves by doing something that makes a difference in people’s lives. It is no secret that the condo market has been on the rise, and as condo dwellers ourselves we were not satisfied with the cleaning services out there. So we decided to start our own.',
            'Having started from the bottom, we can see the impact we have made on the cleaning industry, and so can our clients. From large property management firms to home owners and unit managers, we attract a variety of customers. In addition to top quality cleaning services, affordable prices and years of service industry experience, our clients trust us because we take their needs into account — truly becoming their partners-in-clean.',
            'Maid4Condos has been in business since 2014. We are a family run business who truly cares about each and every client we have the opportunity to service.',
        ],
        'promise' => [
            '100% satisfaction guarantee',
            'Attention to detail',
            'Personal touch',
            'Timely & flexible service',
            'Well supervised, master class trained & certified staff',
            'Worry-free & convenient experience',
            'Customer service that goes above & beyond',
            'Fully insured with 5,000,000 in liability',
            'All staff are bonded',
            'All staff covered by WSIB',
            'All staff background checked & cleared',
        ],
        'memberships' => [
            'Maid4Condos is a member of ISSA and ARCSI — the North American associations for commercial and residential cleaning — so we stay current with the latest technology and industry trends.',
            'All Maid4Condos staff are employees, not independent contractors. They are background checked, master class trained and certified, covered by WSIB, bonded and covered by 5,000,000 in liability insurance.',
        ],
        'not_included' => [
            'Inside or hard-to-reach light fixtures, exterior windows, blinds, drapes or shades',
            'Inside dishwashers, washing machines or hood fans',
            'Cleaning during or after an infestation',
            'Moving anything heavier than 30 lbs',
            'Climbing higher than 2 ft on a ladder or step stool',
            'Exterior or outdoor cleaning, balconies included',
            'Pet or human waste and bodily fluids',
            'Mold, grease and mildew restoration',
            'Inside fireplaces, soot or ashes',
            'Ironing or clothes folding (folding is included with a laundry extra)',
            'Commercial carpet cleaning or shampooing — we can refer a partner',
        ],
    ],

    // -----------------------------------------------------------------------
    // FAQs (source: maid4condos.com/faqs)
    // -----------------------------------------------------------------------
    'faqs' => [
        ['category' => 'About Maid4Condos', 'question' => 'Do you offer a satisfaction guarantee?', 'answer' => 'Yes. If you are not 100% satisfied with the quality of cleaning of any of the serviced areas, and your home is as described and in average condition, and you advise the office within 24 hours after your service, Maid4Condos will send a cleaner back to address any areas in which we fell short within 3 days of your original scheduled cleaning.'],
        ['category' => 'About Maid4Condos', 'question' => 'How long has Maid4Condos been in business?', 'answer' => 'Maid4Condos has been in business since 2014. We are a family run business who truly cares about each and every client we have the opportunity to service.'],
        ['category' => 'About Maid4Condos', 'question' => 'Are you bonded and insured?', 'answer' => 'Yes. Maid4Condos is very selective with our team members — we hire for character and train for skill. All staff are employees of Maid4Condos and not independent contractors, are background checked, cleaning master class trained and certified. Maid4Condos carries all necessary insurance and coverage including 5,000,000 in liability, all our staff are covered by WSIB and are all bonded.'],
        ['category' => 'About Maid4Condos', 'question' => 'Are your cleaning staff true employees or independent contractors?', 'answer' => 'All Maid4Condos staff are true employees and not independent contractors. All have been fully trained and have various certification levels based on their experience and training received. All are background checked, cleaning master class trained and certified, have WSIB coverage, are bonded and hold 5M liability coverage.'],
        ['category' => 'About Maid4Condos', 'question' => 'What is your service area?', 'answer' => 'We currently service within the GTA and surrounding areas, including Downtown Toronto, Liberty Village, Queen West, King West, Fort York, City Place, Lakeshore Blvd, the Distillery District, Yorkville and North York. To confirm we service your specific area, send us your postal code with your quote request.'],
        ['category' => 'About Maid4Condos', 'question' => 'Is Maid4Condos part of any organisations or associations?', 'answer' => 'Yes. Maid4Condos is a member of ISSA and ARCSI, which are the North American associations for commercial and residential cleaning. These resources help ensure we are always aware of the latest technology and industry trends so we can provide the best possible cleaning service to our clients.'],
        ['category' => 'About Maid4Condos', 'question' => 'Do you offer competitive rates?', 'answer' => 'We continue to be recognised as a convenient, affordable and reliable service. There are independent cleaners and companies who offer lower rates because they do not pay for liability insurance, WSIB (workers compensation) or offer any protection for their clients. Maid4Condos prides itself in providing these benefits, giving peace of mind to our customers. We treat, value and compensate our staff well, in turn creating passionate individuals who uphold the Maid4Condos cleaning standards.'],

        ['category' => 'Booking', 'question' => 'How can I get a quote or book a cleaning?', 'answer' => 'Use our quote form. Tell us your neighbourhood and your home details — bedrooms, bathrooms, approximate square footage, the type of clean and how often you would like us — and we will confirm your quote and availability.'],
        ['category' => 'Booking', 'question' => 'What type of cleanings does Maid4Condos offer?', 'answer' => 'We provide Basic, Basic Plus, Deep and Deep Plus cleaning packages, plus a specialist Move In / Move Out package for empty or vacant homes. Recurring AutoPilot schedules are available on weekly, bi-weekly and monthly frequencies.'],
        ['category' => 'Booking', 'question' => 'Can I book a specific date and time?', 'answer' => 'Yes. During the booking process you are able to select a service date and arrival window. Our scheduling manager receives your booking and sends a confirmation, and you will be notified of the status of your booking as it progresses.'],
        ['category' => 'Booking', 'question' => 'Do you arrive at an exact time?', 'answer' => 'We use either 2 hour arrival windows, or a flexible arrival window which means we will clean between 9am and 5pm. You select this during the booking process. We provide an estimated arrival time to allow for factors beyond our control such as traffic conditions, lockouts, and customers adding services or cancellations.'],
        ['category' => 'Booking', 'question' => 'How can I provide access to the cleaners?', 'answer' => 'During the booking process you can choose from: you will be home, key at concierge, smart key pad, or lockbox and instructions. If this changes, please advise our office at your earliest. The best and most efficient methods are key at concierge and lockbox access.'],
        ['category' => 'Booking', 'question' => 'What if I do not know the sizing of my home?', 'answer' => 'Size matters, because size directly relates to the amount of time we allocate to the service. It is important to provide accurate sizing details when booking. If you are not sure of the exact amount, round up or contact us for guidance.'],
        ['category' => 'Booking', 'question' => 'How many cleaners do you send?', 'answer' => 'Depending on the size of the job we send an appropriate number of cleaners. For a 500 sq ft condo we would likely send one cleaner as space is limited, but for larger jobs we can send a team of two or more. Our goal is to be on site for 4 hours or less.'],
        ['category' => 'Booking', 'question' => 'Can I book move in / move out cleaning for a vacant unit?', 'answer' => 'Yes — that is exactly what the Move In / Move Out package is for. It is designed for empty spaces, cleans inside and outside of everything including appliances, cabinets, drawers and air vents, and includes all supplies, equipment and the vacuum.'],

        ['category' => 'Your cleaning', 'question' => 'Are cleaning products included?', 'answer' => 'Yes. Our team arrives equipped with all the basics to clean a home: Comet, Spic&Span, Magic Eraser, fresh cloths and sponges, a feather duster and a professional grade flat mop. The only things we ask you to provide are a vacuum and a toilet brush. If you are booking a post-reno or moving cleaning, the vacuum is included. Otherwise, you can add a vacuum as an extra if you do not have one. If you have a special request for specific products, please provide them for our team to use — for example ceramic cooktop cream or a special floor treatment.'],
        ['category' => 'Your cleaning', 'question' => 'What products do you use?', 'answer' => 'We use Procter & Gamble, Vileda and other leading brands of professional grade products. We are very aware in our product selection to consider the environment and efficiency, which is why our products are biodegradable and safe on the environment. We do not use harsh or dangerous chemicals.'],
        ['category' => 'Your cleaning', 'question' => 'How should I prepare for Maid4Condos staff arrival?', 'answer' => 'There is always that age old rule about whether you should clean before the cleaner comes… the answer is yes. Please pick up all loose items, garbage and debris, and loose articles of clothing from floors, table tops and countertops. This ensures our staff use the allocated time cleaning those surfaces rather than picking up your items.'],
        ['category' => 'Your cleaning', 'question' => 'Can I be home during the cleaning?', 'answer' => 'Yes. However we do recommend heading out to run errands, or, like the majority of our clients, leaving your key in a lockbox or with the concierge for us to retrieve. If you are home, please give the cleaner space to get their work done.'],
        ['category' => 'Your cleaning', 'question' => 'Do you clean with pets in the home?', 'answer' => 'Yes we do. We simply ask that you tell us in advance so we can note it on your work order for allergy purposes.'],
        ['category' => 'Your cleaning', 'question' => 'How can I provide special instructions?', 'answer' => 'Provide special instructions on your booking, or reply to any of the emails you have received from us and let us know how we can help add notes to your booking and instructions for the Maid4Condos staff. You can also email our customer support team at bookings@maid4condos.com.'],
        ['category' => 'Your cleaning', 'question' => 'Will I receive any reminders?', 'answer' => 'Yes. Five days before your upcoming cleaning you will receive an email reminder, and three days before you will receive an SMS text reminder. When you receive your email, that is the time to make any special requests or accommodations.'],
        ['category' => 'Your cleaning', 'question' => 'Do you clean appliances?', 'answer' => 'Yes. You can add either the fridge or the oven as extras to your cleaning service. We do not clean inside of washing machines or dishwashers.'],
        ['category' => 'Your cleaning', 'question' => 'Do you offer window cleaning?', 'answer' => 'Yes. We offer interior window cleaning which can be added to your cleaning at the time of booking, or you can call us to add it to an already booked service. We clean interior windows up to 9 ft tall; exterior windows are not included.'],

        ['category' => 'Payment & policies', 'question' => 'What is your cleaning service rate or charge?', 'answer' => 'Our packages range from Basic and Basic Plus to Deep, Deep Plus and Moving cleanings, charged based on property sizing, number of bedrooms, bathrooms and square footage. Extras such as cleaning appliances or bringing additional equipment can be added when you book. As long as accurate sizing is provided and the space is in average condition, the entirety of the package will be provided.'],
        ['category' => 'Payment & policies', 'question' => 'When am I charged for my cleaning?', 'answer' => 'When booking via the website or over the phone you are charged at the time of booking. You are eligible for a full refund adhering to our rescheduling and cancellation policy.'],
        ['category' => 'Payment & policies', 'question' => 'What is your cancellation policy?', 'answer' => 'For scheduled cleanings, Maid4Condos will assess a $50 cancellation fee if a cleaning service is cancelled or rescheduled within 48 hours of your scheduled cleaning. For same day cancellations, lockouts or rescheduling, or if we cannot gain access within 30 minutes of our arrival, we reserve the right to charge the greater of $75 or 50% of the total service fee.'],
        ['category' => 'Payment & policies', 'question' => 'What is your recurring cleaning cancellation policy?', 'answer' => 'Our cancellation policy applies to each visit. To cancel a recurring schedule prior to 4 or more completed visits, you will be charged the difference from your frequency rate to a one-time cleaning fee for prior visits.'],
        ['category' => 'Payment & policies', 'question' => 'Do you offer frequency discounts?', 'answer' => 'Yes. By joining AutoPilot we offer up to 20% off for weekly, bi-weekly and monthly cleaning schedules. Customisable rates can be offered for daily service or high-volume cleaning. Build a custom quote using our quote form, or email bookings@maid4condos.com.'],
        ['category' => 'Payment & policies', 'question' => 'Do I have to sign a contract?', 'answer' => 'No. For our AutoPilot regularly scheduled residential clients you do not need to commit to a contract, but by using our services you do agree to our Cleaning Service Agreement terms. We work very hard to keep you as a valued client. For corporate clients there are separate service agreements and terms.'],
        ['category' => 'Payment & policies', 'question' => 'What if my home is not in average condition or needs more time?', 'answer' => 'Our quoting is designed to be accurate as long as sizing, room count and condition of the space are accurate. Should inaccurate sizing or below-average condition be found, Maid4Condos reserves the right to contact you to request extra time. Should the extra time not be approved, our staff will do their best within the allocated time and you waive your satisfaction guarantee. Additional time, if requested, is at an hourly rate agreed between the client and Maid4Condos at the time of the request. You will not be charged without your approval.'],
        ['category' => 'Payment & policies', 'question' => 'Can I get compensated for referrals?', 'answer' => 'Yes. If you have a Maid4Condos profile you can share your referral code with friends and family. They get $20 off their first cleaning and you get $20 in M4C credit for every referral. Invites are unlimited.'],
        ['category' => 'Payment & policies', 'question' => 'Can I buy a gift card?', 'answer' => 'Yes — you can purchase a gift card for friends and family, and gift cards do not expire.'],
        ['category' => 'Payment & policies', 'question' => 'Can I tip my cleaner?', 'answer' => 'Yes, absolutely. The cleaners love getting recognised for their hard work. The best way is with cash on site during the service. If you were not able to, you can e-transfer a tip to bookings@maid4condos.com and we will forward it directly to the team that serviced your home.'],
        ['category' => 'Payment & policies', 'question' => 'What if there is damage during my clean?', 'answer' => 'Maid4Condos cleaners promise to conduct themselves professionally in your home at all times. In the event of accidental damage, notify our office within 48 hours of your service. We cannot guarantee reimbursement for any damages reported more than 48 hours after the end of the cleaning appointment, and we request that you are accessible to be contacted so we can assess and repair any damages.'],

        ['category' => 'Hours & availability', 'question' => 'What are your hours of operation?', 'answer' => 'Our office is open between 9am and 5pm Monday to Friday, and we service clients between 8am and 6pm daily. We do not currently provide weekend bookings at this time.'],
        ['category' => 'Hours & availability', 'question' => 'Do you work evenings and weekends?', 'answer' => 'We do not work evenings or weekends in residential homes at this time.'],
        ['category' => 'Hours & availability', 'question' => 'Why are some dates on the calendar blocked?', 'answer' => 'We keep our calendar up to date. Should a date be blocked it would likely be because it is a holiday or fully booked. We do recommend booking as far in advance as possible to secure the date you want.'],
        ['category' => 'Hours & availability', 'question' => 'What if my recurring cleaning date falls on a holiday?', 'answer' => 'If your regular schedule lands on a holiday we will change you to the next available date and communicate the change to you. By default we move your cleaning to the following day unless it is already booked. Should that not work for you, simply reply with a request to change and we will accommodate as long as it is not within our cancellation window and the date is available.'],

        ['category' => 'What we do not do', 'question' => 'Is there anything Maid4Condos does not do?', 'answer' => 'To keep our team safe and to set clear expectations, the following are outside our service: inside or hard-to-reach light fixtures, exterior windows, blinds, drapes or shades; inside dishwashers, washing machines or hood fans; cleaning during or after an infestation; moving anything heavier than 30 lbs; climbing more than 2 ft on a ladder or step stool; exterior or outdoor cleaning including balconies; pet or human waste and bodily fluids; mold, grease and mildew restoration; inside fireplaces, soot or ashes; ironing or clothes folding; and commercial carpet cleaning or shampooing. Our cancellation policy applies where we must decline a service on health and safety grounds.'],
        ['category' => 'What we do not do', 'question' => 'What about clutter, heavy items and areas used for storage?', 'answer' => 'We will work around highly cluttered areas to the best of our ability, and the same goes for areas used for storage such as underneath beds and on top of cabinets. We ask that garbage and debris be cleared from floors, countertops and table tops before our arrival so we can clean those surfaces.'],
        ['category' => 'What we do not do', 'question' => 'Do you remove mold, grease or mildew build-up?', 'answer' => 'Maid4Condos does not assume responsibility for the restoration of severely worn, stained or mildewed and mold infested caulking and grout. Some mild pink or mold presence can be normal and we can tackle that. Should a property have a mold infestation that may pose an air quality issue, we reserve the right to remove our staff for health and safety, and our cancellation policy would apply.'],
        ['category' => 'What we do not do', 'question' => 'Do you do post-renovation cleaning?', 'answer' => 'We are a finishing crew, meaning we will do the final detailed cleaning prior to returning a property to clients or delivery. We do not work in construction zones and we do not clean or remove construction debris.'],
    ],

    // -----------------------------------------------------------------------
    // Testimonials (all published on maid4condos.com — none invented)
    // -----------------------------------------------------------------------
    'testimonials' => [
        ['name' => 'Ahmed N', 'location' => 'Toronto', 'service' => null, 'quote' => 'Terrific service, always on time and does more than advertised! These guys are always on time and come with their own equipment which is a great convenience. Very dependable and customer service is A1!'],
        ['name' => 'Aude C.', 'location' => 'Toronto', 'service' => null, 'quote' => 'It was the first time I used this kind of service and I have no regret. It was very clean. I had an appointment very quickly — I definitely recommend Maid4Condos.'],
        ['name' => 'Toronto Mom', 'location' => 'Toronto', 'service' => null, 'quote' => 'You guys ROCK — keep up the great work!'],
        ['name' => 'Jessica', 'location' => 'North York', 'service' => 'Bi-weekly recurring cleaning', 'quote' => 'I have been using Maid4Condos on an occasional basis for the past four years, and recently committed to getting cleaning done by them on a bi-weekly basis. They are very responsive, and their rates are reasonable. I also really appreciate their flexibility. The amount of work that the members of the Maid4Condos team are able to accomplish in a short period of time always amazes me. They are more than willing to use the tools and products we have on hand, and are open to feedback if you are looking for something to be done in a specific way.'],
        ['name' => 'Dave', 'location' => 'Toronto', 'service' => null, 'quote' => 'The cleaning is thorough and a great deal of attention is paid to the smallest of detail; I’m able to leave for work and trust the team to come in, clean everything spotless, and have it ready for when I come home.'],
        ['name' => 'Tom', 'location' => 'Toronto', 'service' => null, 'quote' => 'I discovered Maid4Condos at the Liberty Village Art Crawl and decided to give them a try. I have used them twice now and find them to be exceptional. They pay attention to details and are prompt and reliable and a great value. I will continue to use their services and recommend them to others.'],
        ['name' => 'Amy', 'location' => 'Toronto', 'service' => null, 'quote' => 'I have been using Maid4Condos for almost 2 years and I am very happy with the service. They are extremely professional in their approach, do a thorough job and always make an effort to accommodate my schedule which is often erratic due to my extensive travelling. I trust them with the key to my place and never have to worry about anything.'],
    ],

    // -----------------------------------------------------------------------
    // Primary navigation
    // -----------------------------------------------------------------------
    'navigation' => [
        ['label' => 'Services',    'route' => 'services'],
        ['label' => 'About',       'route' => 'about'],
        ['label' => 'FAQ',         'route' => 'faq'],
        ['label' => 'Testimonials', 'route' => 'testimonials'],
        ['label' => 'Contact',     'route' => 'contact'],
    ],
];
